from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us', views.about, name='about'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('erpnext-retail-industry',views.erp_retail, name='erp-retail'),
    path('erpnext-service-industry',views.erp_services, name='erp-services'),
    path('erpnext-education-industry',views.erp_education, name='erp-education'),
    path('erpnext-manufacturing-industry',views.erp_manufacturing, name='erp-manufacturing'),
    path('frappe-hrms-solutions',views.frappe_hrms, name='frappe-hrms-solutions'),
    path('erpnext-distribution-industry',views.erp_dist, name='erp-dist'),
    path('erpnext-healthcare-industry',views.erp_healthcare, name='erp-healthcare'),
    path('our-privacy-policy', views.privacy_policy, name='privacy_policy'),
    path('apply/<str:slug>', views.apply, name='apply'),
    path('newsletter', views.newsletter, name='newsletter'),
    # path('career',views.career, name='career'),
    path('contact-us', views.contact, name='contact'),
    path('faqs',views.faqs, name='faqs'),
    path('our-vision',views.our_vision, name='our_vision'),
    path('travel',views.travel, name='travel'),
    path('our-team',views.teams, name='team'),
    path('blog',views.blog, name='blog'),
    path('blog/<str:slug>',views.sort_blog, name='sort-blog'),
    # path('blog/<slug:category_id>',views.industry, name='industry'),
    path('blog/<slug:category_id>/<slug:blog_slug>',views.singleblog, name='singleblog'),
    path('blog/<slug:blog_slug>',views.singleblog, name='singleblog'),
    path('request-qoute/', views.request_quote, name='request_quote'),
    path('get_data/', views.get_data, name='get_data'),
    path('companies/', views.CompanyView.as_view(), name='companies'),
    path('services/<slug:service>', views.ServiceView, name='services'),
    path('hire-remote-developer/<slug:developer>', views.HireDeveloperView, name='hire_developer'),
    path('hire-remote-developer', views.developer_category, name='hire_developer_category'),
    path('service', views.service_category, name='service_category'),
    path('hire-remote-erpnext-developer/', views.hire_remote_erpnext_developer, name='hire_remote_erpnext_developer'),
]